# Generated by Django 3.2.18 on 2023-04-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=1, max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
