# Generated by Django 3.2.18 on 2023-04-24 01:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.URLField(default='', verbose_name='Portada Cat'),
            preserve_default=False,
        ),
    ]
